# ============================================================================
# setup-env.ps1 — Generate the pipeline's .env from the deployed Storage Account
# ----------------------------------------------------------------------------
# Run this in YOUR terminal AFTER the Bicep deployment succeeds:
#     ./infra/setup-env.ps1 -ResourceGroup rg-compliance-demo
# It fetches the storage connection string via az and writes ../.env
# (which is git-ignored). Re-run any time to refresh it.
# ============================================================================
param(
    [string]$ResourceGroup = "rg-compliance-demo"
)

$ErrorActionPreference = "Stop"

Write-Host "Looking up storage account in resource group '$ResourceGroup'..." -ForegroundColor Cyan
$storageName = az storage account list -g $ResourceGroup --query "[0].name" -o tsv
if (-not $storageName) { throw "No storage account found in $ResourceGroup. Did the deployment succeed?" }
Write-Host "Found storage account: $storageName" -ForegroundColor Green

$conn = az storage account show-connection-string -g $ResourceGroup -n $storageName --query connectionString -o tsv
if (-not $conn) { throw "Could not retrieve connection string." }

$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot ".env"

$envContent = @"
# Auto-generated by infra/setup-env.ps1 — DO NOT COMMIT (already in .gitignore)
AZURE_STORAGE_CONNECTION_STRING=$conn
AZURE_STORAGE_QUEUE_NAME=tx-events
AZURE_STORAGE_ACCOUNT_NAME=$storageName

# Set to 0 ONLY if Avast/antivirus TLS interception breaks the Azure SDK locally.
AZURE_SSL_VERIFY=1
"@

Set-Content -Path $envPath -Value $envContent -Encoding utf8
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "If L0 later fails with an SSL CERTIFICATE_VERIFY error, set AZURE_SSL_VERIFY=0 in .env and re-run." -ForegroundColor Yellow
